# Generated by Django 5.0 on 2024-02-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
