# Generated by Django 5.0 on 2024-02-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blog_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
