# Generated by Django 4.1.13 on 2024-03-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='description',
        ),
    ]
