# Generated by Django 4.1.13 on 2024-03-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_content_blog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='content',
        ),
    ]
